// Platform features seed — internal reference library of what Mhwar delivers.
// Each feature = a capability/service offered on the platform.
// families group capabilities; useWith links to related use-case patterns; templates links to email/WhatsApp templates that use it.
// Each feature carries: status (live/dev/planned/idea), priority (p0-p3), notes (free text).

const UC_FEATURE_STATUSES = [
  { id: 'live',     label: 'منشور',       short: 'منشور على الموقع',        hue: 145, dot: '●' },
  { id: 'dev',      label: 'قيد التطوير',  short: 'قيد التطوير',             hue: 45,  dot: '◐' },
  { id: 'planned',  label: 'مخطّط',        short: 'ضمن خطة المنتج',          hue: 220, dot: '○' },
  { id: 'idea',     label: 'اقتراح',       short: 'فكرة مقترحة (غير مؤكّدة)', hue: 265, dot: '◇' },
];

const UC_FEATURE_PRIORITIES = [
  { id: 'p0', label: 'حرجة',    short: 'لا غنى عنها',   hue: 0,   rank: 4 },
  { id: 'p1', label: 'عالية',   short: 'تميّزنا بوضوح',  hue: 25,  rank: 3 },
  { id: 'p2', label: 'متوسطة',  short: 'إضافة قيّمة',   hue: 85,  rank: 2 },
  { id: 'p3', label: 'منخفضة',  short: 'تحسين تدريجي',  hue: 205, rank: 1 },
];

const UC_FEATURE_FAMILIES = [
  { id: 'channels',     label: 'قنوات التواصل',       short: 'قنوات',     hue: 145, icon: '⇆', desc: 'واتساب · إيميل · SMS — قنوات موحّدة بعلامة بيضاء' },
  { id: 'events',       label: 'الفعاليات والتذاكر',  short: 'فعاليات',   hue: 35,  icon: '◈', desc: 'دعوات · RSVP · تذاكر QR · صفحات هبوط للفعاليات' },
  { id: 'communities',  label: 'إدارة المجتمعات',     short: 'مجتمعات',   hue: 265, icon: '○', desc: 'صفحة مجتمع · قنوات · أنماط تواصل جاهزة' },
  { id: 'audience',     label: 'إدارة الجمهور',       short: 'جمهور',     hue: 310, icon: '⚇', desc: 'قوائم · شرائح · استيراد · إلغاء اشتراك' },
  { id: 'campaigns',    label: 'الحملات والإرسال',    short: 'حملات',     hue: 25,  icon: '➤', desc: 'جدولة · A/B · توقيت ذكي · رحلات متعدّدة الخطوات' },
  { id: 'identity',     label: 'الهوية والدخول',      short: 'دخول',      hue: 220, icon: '◉', desc: 'OTP · كلمات مرور · Nafath · إدارة فرق' },
  { id: 'governance',   label: 'الحوكمة والسجلات',    short: 'حوكمة',     hue: 195, icon: '⊡', desc: 'محاضر · تصويت · أرشفة · قنوات رسمية' },
  { id: 'issuance',     label: 'الإصدار والشهادات',   short: 'إصدار',     hue: 45,  icon: '◇', desc: 'شهادات حضور · رموز تحقق · إنتاج PDF' },
  { id: 'analytics',    label: 'القياس والتحليل',     short: 'قياس',      hue: 175, icon: '△', desc: 'لوحات أداء · تقارير وصول · تتبّع فوري' },
  { id: 'automation',   label: 'الأتمتة والنشرات',    short: 'أتمتة',     hue: 280, icon: '⇌', desc: 'تذكيرات · نشرات دورية · رحلات مبنية على الحدث' },
  { id: 'payments',     label: 'الدفع والفوترة',      short: 'دفع',       hue: 95,  icon: '◐', desc: 'تحصيل إلكتروني · فواتير · اشتراكات' },
  { id: 'ai',           label: 'الذكاء الاصطناعي',    short: 'AI',        hue: 285, icon: '✻', desc: 'صياغة محتوى · ردّ ذكي · اقتراحات توقيت' },
  { id: 'integrations', label: 'التكاملات والـ API',  short: 'تكاملات',   hue: 185, icon: '⊸', desc: 'Webhooks · Zapier · BYO-Meta · BYO-Email' },
  { id: 'brand',        label: 'العلامة والتخصيص',    short: 'علامة',     hue: 0,   icon: '◆', desc: 'علامة بيضاء · هوية مخصّصة · نطاقات' },
  { id: 'legal',        label: 'قانوني ومرجعي',        short: 'قانوني',    hue: 230, icon: '§', desc: 'شروط · خصوصية · PDPL · DPA · حوكمة بيانات' },
];

// Helper to reduce boilerplate: defaults status='live', priority='p2', notes=''
function _f(x) {
  return {
    status: 'live', priority: 'p2', notes: '',
    channels: [], useWith: [], templates: [],
    ...x,
  };
}

const UC_FEATURES_SEED = [
  // ===== Channels — CORE =====
  _f({ id: 'ch.whatsapp', family: 'channels', hue: 145, icon: '⌬', name: 'واتساب — قنوات رسمية',
    shortAr: 'قوالب معتمدة من Meta', status: 'live', priority: 'p0',
    desc: 'إرسال قوالب واتساب رسمية (Utility/Marketing/OTP) من حساب واتساب الأعمال المعتمد — مع متغيرات ديناميكية وأزرار CTA ونسخ الرموز.',
    channels: ['whatsapp'], templates: ['event-invite','rsvp-confirm','reminder','access-link','certificate','feedback','otp','payment'] }),
  _f({ id: 'ch.email', family: 'channels', hue: 205, icon: '✉', name: 'بريد إلكتروني تعاملي',
    shortAr: 'إيميلات HTML بهوية العميل', status: 'live', priority: 'p0',
    desc: 'إرسال إيميلات معاملات من نطاقك (SPF/DKIM) بقوالب HTML مخصّصة — دعوات، تأكيدات، شهادات، تذكيرات، نشرات.',
    channels: ['email'], templates: ['welcome','event-invite','rsvp-confirm','reminder','certificate','client-newsletter'] }),
  _f({ id: 'ch.sms', family: 'channels', hue: 95, icon: '▣', name: 'SMS للجمهور الواسع',
    shortAr: 'رسائل نصية سريعة ومضمونة', status: 'planned', priority: 'p2',
    desc: 'إرسال SMS بعلامة المرسل المعتمدة — للطوارئ، التذكيرات الحرجة، والجمهور الذي لا يستخدم التطبيقات.',
    channels: ['sms'] }),
  _f({ id: 'ch.inapp', family: 'channels', hue: 265, icon: '●', name: 'إشعارات داخل المنصّة',
    shortAr: 'إشعارات مباشرة داخل البوابة', status: 'dev', priority: 'p2',
    desc: 'إشعارات ظاهرة داخل لوحة العضو — محدّثات مجتمع، إعلانات، ردود نقاشات.',
    channels: ['inapp'] }),
  _f({ id: 'ch.telegram', family: 'channels', hue: 210, icon: '✈', name: 'Telegram (قناة/بوت)',
    shortAr: 'قناة تليجرام اختيارية', status: 'idea', priority: 'p3',
    desc: 'قناة أو بوت تليجرام للمجتمعات التي يفضّل جمهورها تليجرام — مع نفس محرّك القوالب.',
    channels: ['inapp'], notes: 'مطلوب لبعض المجتمعات التقنية' }),

  // ===== BYO / Integrations =====
  _f({ id: 'in.byo_meta', family: 'integrations', hue: 145, icon: '⌬', name: 'إرسال من حساب Meta الخاص بالعميل',
    shortAr: 'BYO — WhatsApp Business Account', status: 'dev', priority: 'p0',
    desc: 'ربط حساب Meta/WhatsApp Business الخاص بالعميل مباشرةً — كل الرسائل تخرج من اسمه التجاري وبرقمه المعتمد، بدون وسيط. يحافظ على علاقة العميل بـ Meta ويمنحه تحكّماً كاملاً بالكوتا والحساب.',
    channels: ['whatsapp'], useWith: ['مفتوح','مغلق','هجين'],
    notes: 'تفاضل استراتيجي ضد المنافسين الذين يوحّدون الإرسال من حسابهم' }),
  _f({ id: 'in.byo_email', family: 'integrations', hue: 205, icon: '✉', name: 'إرسال من نطاق بريد العميل',
    shortAr: 'BYO — SMTP / SES / Mailgun', status: 'dev', priority: 'p0',
    desc: 'ربط نطاق العميل (SPF + DKIM + DMARC) أو SMTP/SES/Mailgun الخاص به — كل إيميل يصل من عنوان العميل مباشرة بدون إشارة لمحور. يرفع معدّل الوصول ويحمي السمعة البريدية.',
    channels: ['email'], useWith: ['مفتوح','مغلق','هجين'],
    notes: 'يرفع معدّل التسليم ويحافظ على سمعة نطاق العميل' }),
  _f({ id: 'in.webhook', family: 'integrations', hue: 185, icon: '⊸', name: 'Webhooks للمطوّرين',
    shortAr: 'أحداث فورية لأنظمة العميل', status: 'planned', priority: 'p2',
    desc: 'إرسال أحداث المنصّة (تأكيد حضور، دفع، فشل تسليم…) إلى webhook العميل فوراً — للتكامل مع CRM أو ERP.',
    channels: ['inapp'] }),
  _f({ id: 'in.api', family: 'integrations', hue: 185, icon: '▤', name: 'REST API عامّة',
    shortAr: 'API لإرسال وإدارة الأعضاء', status: 'planned', priority: 'p2',
    desc: 'API موثّقة للعمليات الأساسية: إضافة عضو، إرسال رسالة، استعلام حالة، تصدير تقرير — مع توثيق Swagger.',
    channels: ['inapp'] }),
  _f({ id: 'in.zapier', family: 'integrations', hue: 35, icon: '⚡', name: 'Zapier / Make',
    shortAr: 'تكاملات بدون كود', status: 'idea', priority: 'p3',
    desc: 'اتصال مع +3000 تطبيق عبر Zapier/Make — بدون كتابة كود: Google Sheets، Notion، HubSpot، Slack.',
    channels: ['inapp'] }),

  // ===== Events & Tickets =====
  _f({ id: 'ev.landing', family: 'events', hue: 245, icon: '◈', name: 'صفحة هبوط للفعالية',
    shortAr: 'صفحة ويب كاملة بهوية العميل', status: 'live', priority: 'p0',
    desc: 'صفحة ويب للفعالية: هيرو، أجندة، متحدّثون، مقر، تسجيل، تأكيد — بهوية العميل ولون مخصّص.',
    channels: ['web'], useWith: ['مفتوح','هجين'], templates: ['landing-page','landing-page-dark'] }),
  _f({ id: 'ev.rsvp', family: 'events', hue: 245, icon: '✓', name: 'RSVP وتأكيد الحضور',
    shortAr: 'تدفّق تأكيد → تذكرة', status: 'live', priority: 'p0',
    desc: 'نموذج تأكيد الحضور يتحوّل فوراً إلى تذكرة QR — مع إمكانية التعديل أو الإلغاء حتى الموعد.',
    channels: ['web','email','whatsapp'], templates: ['rsvp-confirm','event-invite'] }),
  _f({ id: 'ev.qr_ticket', family: 'events', hue: 35, icon: '▦', name: 'تذكرة QR',
    shortAr: 'رمز تحقق للدخول', status: 'live', priority: 'p0',
    desc: 'تذكرة موحّدة بـ QR فريد لكل حاضر — تُرسل عبر الواتساب والإيميل وتُقرأ عند البوابة.',
    channels: ['whatsapp','email','web'], templates: ['rsvp-confirm','access-link'] }),
  _f({ id: 'ev.checkin', family: 'events', hue: 35, icon: '⌖', name: 'نظام دخول عند البوّابة',
    shortAr: 'تطبيق مسح QR للموظفين', status: 'dev', priority: 'p1',
    desc: 'تطبيق موبايل للموظّفين لمسح QR وتسجيل الدخول الفعلي — مع إحصائيات فورية للحضور.',
    channels: ['inapp'] }),
  _f({ id: 'ev.reminders', family: 'events', hue: 45, icon: '⏰', name: 'تذكيرات آلية قبل الفعالية',
    shortAr: '24 سا · 2 سا · عند البداية', status: 'live', priority: 'p1',
    desc: 'تسلسل تذكيرات تلقائي: قبل يوم، قبل ساعتين، عند البدء — مع روابط بث مباشر وخرائط.',
    channels: ['whatsapp','email','sms'], templates: ['reminder','access-link'] }),
  _f({ id: 'ev.live_access', family: 'events', hue: 0, icon: '◉', name: 'روابط بث حيّة',
    shortAr: 'روابط سرّية شخصيّة', status: 'live', priority: 'p1',
    desc: 'رابط دخول مخصّص لكل حاضر — يُعطَّل بعد 24 ساعة ولا يمكن مشاركته.',
    channels: ['whatsapp','email'], templates: ['access-link'] }),
  _f({ id: 'ev.feedback', family: 'events', hue: 170, icon: '✎', name: 'استبيانات ما بعد الفعالية',
    shortAr: 'تقييم سريع 😍🙂😐', status: 'live', priority: 'p1',
    desc: 'أزرار سريعة + استبيان كامل اختياري — نتائج مجمّعة في لوحة القياس.',
    channels: ['whatsapp','email'], templates: ['feedback','after-event'] }),
  _f({ id: 'ev.speaker', family: 'events', hue: 35, icon: '◊', name: 'دعوات متحدّثين وVIP',
    shortAr: 'مسار دعوات مختلف للشركاء', status: 'live', priority: 'p1',
    desc: 'قوالب دعوة منفصلة للمتحدثين والشخصيات المهمّة — مع تفاصيل فنّية ومتطلبات العرض.',
    channels: ['email','whatsapp'], templates: ['speaker-invite','invite-designer','event-update','event-published'] }),
  _f({ id: 'ev.designer', family: 'events', hue: 35, icon: '◈', name: 'مصمّم الدعوات المرئي',
    shortAr: 'تصاميم جاهزة للعميل — PNG/PDF', status: 'live', priority: 'p1',
    desc: 'محرّر دعوات بصري: اختيار نمط، تخصيص الألوان والصور والخطوط، تصدير PNG/PDF جاهز للإرسال.',
    channels: ['web'], templates: ['invite-designer'] }),
  _f({ id: 'ev.agenda', family: 'events', hue: 245, icon: '▥', name: 'إدارة أجندة متعدّدة المسارات',
    shortAr: 'مسارات متوازية + جلسات', status: 'planned', priority: 'p2',
    desc: 'فعاليات متعدّدة المسارات — كل حاضر يختار جدوله الخاص، ويستلم تذكرة شخصية بجلساته.',
    channels: ['web'] }),
  _f({ id: 'ev.waitlist', family: 'events', hue: 265, icon: '⇉', name: 'قوائم انتظار للفعاليات',
    shortAr: 'بوّابة دخول عند الامتلاء', status: 'live', priority: 'p2',
    desc: 'عند امتلاء المقاعد: تسجيل في قائمة الانتظار، إشعار آلي عند توفّر مقعد، ترقية تلقائية.',
    channels: ['email','whatsapp'], templates: ['waitlist'] }),

  // ===== Communities =====
  _f({ id: 'com.page', family: 'communities', hue: 265, icon: '▭', name: 'صفحة مجتمع مستقلّة',
    shortAr: 'هوية وقنوات لكل مجتمع', status: 'live', priority: 'p0',
    desc: 'صفحة منفصلة لكل مجتمع: هويّته ولونه وقنواته وأعضاءه وأنماط تواصله — بدل خلطها في أداة واحدة.',
    channels: ['web'], useWith: ['مفتوح','مغلق','هجين'] }),
  _f({ id: 'com.patterns', family: 'communities', hue: 265, icon: '◎', name: 'أنماط تواصل جاهزة',
    shortAr: 'مفتوح · مغلق · هجين', status: 'live', priority: 'p1',
    desc: 'ثلاثة أنماط جذرية (Open/Closed/Hybrid) كل منها يحمل قواعده وقوالبه فور تفعيله.',
    channels: ['web'], useWith: ['مفتوح','مغلق','هجين'] }),
  _f({ id: 'com.traits', family: 'communities', hue: 265, icon: '⊹', name: 'خصائص قابلة للتركيب',
    shortAr: '9 صفات توصف بها المجتمعات', status: 'live', priority: 'p1',
    desc: 'خصائص مركّبة: رسمي · داخلي · تفاعلي · بعلامة-بيضاء · مدفوع · مجاني · إرسال-فقط · خارجي · بعلامة-محور.',
    channels: ['web'], useWith: ['مفتوح','مغلق','هجين'] }),
  _f({ id: 'com.channels', family: 'communities', hue: 145, icon: '⎍', name: 'قنوات واتساب منفصلة للمجتمع',
    shortAr: 'قناة لكل مجتمع — بلا خلط', status: 'live', priority: 'p1',
    desc: 'قناة واتساب مستقلة لكل مجتمع بدلاً من قروبات مبعثرة — مع أرشفة آلية وصلاحيات.',
    channels: ['whatsapp'], useWith: ['مفتوح','مغلق','هجين'] }),
  _f({ id: 'com.newsletter', family: 'communities', hue: 310, icon: '▤', name: 'نشرة المجتمع',
    shortAr: 'نشرة بريدية لكل مجتمع', status: 'live', priority: 'p1',
    desc: 'نشرة دورية مخصّصة لكل مجتمع — إصدار أسبوعي/شهري مع تحليلات فتح وتفاعل.',
    channels: ['email'], templates: ['client-newsletter','platform-newsletter','weekly-digest'] }),
  _f({ id: 'com.discussion', family: 'communities', hue: 265, icon: '◩', name: 'منتدى نقاشات داخل البوّابة',
    shortAr: 'مواضيع · ردود · إشعارات', status: 'idea', priority: 'p3',
    desc: 'منتدى نقاشات مخصّص لكل مجتمع داخل البوّابة — بديل عن قروبات الواتساب الفوضوية.',
    channels: ['web','inapp'] }),

  // ===== Audience =====
  _f({ id: 'au.contacts', family: 'audience', hue: 310, icon: '⚇', name: 'قاعدة جهات اتصال موحّدة',
    shortAr: 'عضو واحد · قنوات متعدّدة', status: 'live', priority: 'p0',
    desc: 'ملف موحّد لكل عضو يربط رقم الواتساب والإيميل والهاتف — تفاصيل كاملة وتاريخ رسائل مُجمّع.',
    channels: ['inapp'] }),
  _f({ id: 'au.segments', family: 'audience', hue: 310, icon: '⊞', name: 'شرائح ديناميكية',
    shortAr: 'شرائح تُحدَّث تلقائياً', status: 'dev', priority: 'p1',
    desc: 'إنشاء شرائح بقواعد ديناميكية: "من حضروا ≥3 فعاليات"، "الأعضاء الجدد في آخر 30 يوم" — تتحدّث تلقائياً.',
    channels: ['inapp'] }),
  _f({ id: 'au.import', family: 'audience', hue: 310, icon: '↓', name: 'استيراد/تصدير CSV و Excel',
    shortAr: 'نقل بيانات آمن', status: 'live', priority: 'p0',
    desc: 'استيراد جهات اتصال من Excel/CSV مع تطابق الأعمدة — وتصدير كامل البيانات عند الحاجة.',
    channels: ['inapp'] }),
  _f({ id: 'au.unsubscribe', family: 'audience', hue: 0, icon: '✕', name: 'إلغاء اشتراك آلي',
    shortAr: 'احترام خيار العضو', status: 'dev', priority: 'p0',
    desc: 'رابط إلغاء اشتراك في كل إيميل + أمر STOP في واتساب — حذف فوري من كل القوائم واحترام القرار.',
    channels: ['email','whatsapp'], notes: 'ضروري قانونياً' }),
  _f({ id: 'au.preferences', family: 'audience', hue: 310, icon: '⚙', name: 'صفحة تفضيلات العضو',
    shortAr: 'العضو يختار قنواته', status: 'planned', priority: 'p1',
    desc: 'صفحة يصل لها العضو عبر رابط شخصي — يختار فيها: أي قنوات يستقبل، أي نوع محتوى، تردّد.',
    channels: ['web'] }),
  _f({ id: 'au.bounce', family: 'audience', hue: 0, icon: '↺', name: 'إدارة الأخطاء والارتدادات',
    shortAr: 'تنظيف تلقائي للقوائم', status: 'dev', priority: 'p1',
    desc: 'تتبّع الإيميلات المرتدّة وأرقام الواتساب الخاطئة — عزلها تلقائياً ومحاولة إعادة تأهيلها.',
    channels: ['email','whatsapp'] }),

  // ===== Campaigns =====
  _f({ id: 'cm.send_now', family: 'campaigns', hue: 25, icon: '➤', name: 'حملة فورية',
    shortAr: 'إرسال جماعي بنقرة', status: 'live', priority: 'p0',
    desc: 'إرسال رسالة لقائمة أو شريحة — معاينة قبل الإرسال، تتبّع فوري للتسليم والفتح.',
    channels: ['whatsapp','email','sms'] }),
  _f({ id: 'cm.schedule', family: 'campaigns', hue: 25, icon: '⌚', name: 'جدولة إرسال',
    shortAr: 'إرسال في الوقت المناسب', status: 'live', priority: 'p1',
    desc: 'جدولة حملات في المستقبل — بتوقيت محدّد لكل منطقة زمنية عند الحاجة.',
    channels: ['whatsapp','email','sms'] }),
  _f({ id: 'cm.ab_test', family: 'campaigns', hue: 25, icon: '◇', name: 'اختبار A/B',
    shortAr: 'صياغتان · نتيجة أفضل', status: 'planned', priority: 'p2',
    desc: 'اختبار نسختين من نفس الرسالة على عيّنة صغيرة، ثم إرسال النسخة الأفضل تلقائياً للباقي.',
    channels: ['whatsapp','email'] }),
  _f({ id: 'cm.sto', family: 'campaigns', hue: 25, icon: '◉', name: 'توقيت إرسال ذكي',
    shortAr: 'Send Time Optimization', status: 'idea', priority: 'p2',
    desc: 'AI يتعلّم من سلوك كل عضو ويرسل له في أنسب وقت لفتح الرسائل.',
    channels: ['whatsapp','email'] }),
  _f({ id: 'cm.drip', family: 'campaigns', hue: 25, icon: '⋯', name: 'حملات متعدّدة الخطوات (Drip)',
    shortAr: 'سلسلة رسائل متتابعة', status: 'planned', priority: 'p1',
    desc: 'سلسلة رسائل مجدولة على أسابيع/أشهر — مع تفرّعات حسب سلوك العضو (فتح، نقر، ردّ).',
    channels: ['whatsapp','email'] }),
  _f({ id: 'cm.tz', family: 'campaigns', hue: 25, icon: '⧈', name: 'منطقة زمنية لكل عضو',
    shortAr: 'احترم توقيته الصحيح', status: 'idea', priority: 'p2',
    desc: 'إرسال في الساعة المناسبة حسب المنطقة الزمنية لكل عضو — لا مزعج في منتصف الليل.',
    channels: ['whatsapp','email'] }),

  // ===== Identity & Access =====
  _f({ id: 'id.otp', family: 'identity', hue: 35, icon: '✦', name: 'تحقّق برمز OTP',
    shortAr: 'دخول آمن بستّة أرقام', status: 'live', priority: 'p0',
    desc: 'OTP عبر واتساب/SMS/إيميل — صلاحية 10 دقائق، زر نسخ الرمز، حماية من التكرار.',
    channels: ['whatsapp','sms','email'], templates: ['otp'] }),
  _f({ id: 'id.password', family: 'identity', hue: 220, icon: '⎔', name: 'استعادة كلمة المرور',
    shortAr: 'رابط إعادة تعيين', status: 'live', priority: 'p1',
    desc: 'رابط آمن صالح لساعة واحدة — لإعادة تعيين كلمة المرور عند النسيان.',
    channels: ['email'], templates: ['password-reset'] }),
  _f({ id: 'id.team', family: 'identity', hue: 220, icon: '◉', name: 'دعوات فريق وصلاحيات',
    shortAr: 'أدوار · مدير · محرّر · مراقب', status: 'live', priority: 'p1',
    desc: 'دعوة أعضاء فريقك بأدوار محدّدة — إرسال دعوة بريدية، قبول عبر رابط، توزيع صلاحيات حسب الدور.',
    channels: ['email'], templates: ['team-invite','invite-designer'] }),
  _f({ id: 'id.welcome', family: 'identity', hue: 145, icon: '◉', name: 'رحلة الترحيب',
    shortAr: 'أوّل لقاء مع العضو', status: 'live', priority: 'p1',
    desc: 'إيميل ترحيبي مخصّص + خطوات التأهيل — تكوين انطباع أول قوي للعضو الجديد.',
    channels: ['email'], templates: ['welcome'] }),
  _f({ id: 'id.nafath', family: 'identity', hue: 145, icon: '⎋', name: 'تحقّق بنفاذ (Nafath)',
    shortAr: 'هوية رقمية سعودية', status: 'idea', priority: 'p2',
    desc: 'تكامل مع نفاذ للتحقق من الهوية الرسمية — مطلوب لبعض المجالس والجهات التنظيمية.',
    channels: ['web'], notes: 'مهم للقطاع الحكومي والجمعيات' }),

  // ===== Governance =====
  _f({ id: 'gv.sessions', family: 'governance', hue: 195, icon: '⊡', name: 'جلسات ومحاضر',
    shortAr: 'تسجيل منظّم للاجتماعات', status: 'planned', priority: 'p1',
    desc: 'صفحة لكل جلسة: جدول أعمال، محضر، قرارات، مرفقات — بدل أرشفة يدوية مبعثرة.',
    channels: ['web'], useWith: ['مغلق','هجين'] }),
  _f({ id: 'gv.voting', family: 'governance', hue: 195, icon: '✓', name: 'تصويت وقرارات موثّقة',
    shortAr: 'تصويت رسمي بالوكالة', status: 'planned', priority: 'p2',
    desc: 'تصويت سرّي/معلن، بالوكالة، على القرارات — محضر نتائج موقّع رقمياً.',
    channels: ['web'], useWith: ['مغلق'] }),
  _f({ id: 'gv.archive', family: 'governance', hue: 195, icon: '▥', name: 'أرشيف بحثيّ',
    shortAr: 'بحث كامل في القرارات', status: 'planned', priority: 'p2',
    desc: 'فهرسة كاملة لكل القرارات والمحاضر والمرفقات — بحث فوري بالكلمة والتاريخ.',
    channels: ['web'], useWith: ['مغلق','هجين'] }),
  _f({ id: 'gv.official', family: 'governance', hue: 195, icon: '▦', name: 'قنوات رسمية',
    shortAr: 'قنوات معتمدة للجهات المنظّمة', status: 'dev', priority: 'p1',
    desc: 'قناة بعلامة بيضاء تُستخدم كمرجع رسمي للهيئات والجهات الحكومية والتنظيمية.',
    channels: ['web','email','whatsapp'], useWith: ['مغلق'] }),

  // ===== Issuance =====
  _f({ id: 'is.certificate', family: 'issuance', hue: 45, icon: '◇', name: 'شهادات حضور/إتمام',
    shortAr: 'PDF بهوية مخصّصة', status: 'live', priority: 'p1',
    desc: 'شهادة PDF بهوية العميل — إصدار تلقائي للحاضرين، رمز تحقق فريد، إضافة إلى LinkedIn.',
    channels: ['email','whatsapp','web'], templates: ['certificate'] }),
  _f({ id: 'is.verify', family: 'issuance', hue: 45, icon: '✓', name: 'رابط تحقّق عام',
    shortAr: 'صفحة تأكيد صحّة المستند', status: 'dev', priority: 'p2',
    desc: 'رابط عام يُثبت صحّة أي شهادة أو وثيقة صادرة — رقم فريد وتاريخ ومستقبِل.',
    channels: ['web'] }),
  _f({ id: 'is.templates', family: 'issuance', hue: 45, icon: '◈', name: 'محرّر قوالب الشهادات',
    shortAr: 'صمّم شهادتك بلا تصميم خارجي', status: 'planned', priority: 'p2',
    desc: 'محرّر بصري لقوالب الشهادات داخل المنصّة — ألوان، شعارات، توقيعات، خطوط عربية وإنجليزية.',
    channels: ['web'] }),

  // ===== Analytics =====
  _f({ id: 'an.dashboard', family: 'analytics', hue: 175, icon: '△', name: 'لوحة قياس موحّدة',
    shortAr: 'وصول · حضور · تفاعل — بأرقام', status: 'live', priority: 'p1',
    desc: 'لوحة واحدة لكل المجتمعات: معدّلات الوصول والفتح والرد والتفاعل — بدلاً من تخمين نتائج كل حملة.',
    channels: ['web'], useWith: ['مفتوح','مغلق','هجين'] }),
  _f({ id: 'an.events', family: 'analytics', hue: 175, icon: '◉', name: 'تحليل الفعاليات',
    shortAr: 'تقرير ما بعد كل فعالية', status: 'live', priority: 'p1',
    desc: 'معدّل التأكيد · الحضور الفعلي · الرضا · شهادات مُصدرة · أكثر الجلسات تفاعلاً.',
    channels: ['web'] }),
  _f({ id: 'an.tracking', family: 'analytics', hue: 175, icon: '◦', name: 'تتبّع الوصول الفوري',
    shortAr: 'فُتح · رُدّ · نُقر', status: 'live', priority: 'p1',
    desc: 'تتبّع فوري لحالة كل رسالة: أُرسلت، وصلت، فُتحت، رُدّ عليها، نُقر على زر.',
    channels: ['whatsapp','email','sms'] }),
  _f({ id: 'an.export', family: 'analytics', hue: 175, icon: '↥', name: 'تصدير التقارير',
    shortAr: 'PDF · Excel · مجدولة', status: 'planned', priority: 'p2',
    desc: 'تصدير أي تقرير إلى PDF أو Excel — يدوياً أو بجدولة أسبوعية/شهرية لأصحاب المصلحة.',
    channels: ['email'] }),

  // ===== Automation =====
  _f({ id: 'au.newsletter', family: 'automation', hue: 280, icon: '▤', name: 'نشرات دورية آلية',
    shortAr: 'أسبوعية · شهرية · حسب الطلب', status: 'live', priority: 'p1',
    desc: 'إنشاء وجدولة نشرات متكرّرة — لكل مجتمع جدوله ومحتواه.',
    channels: ['email'], templates: ['client-newsletter','platform-newsletter','weekly-digest'] }),
  _f({ id: 'au.journeys', family: 'automation', hue: 280, icon: '⇌', name: 'رحلات مبنيّة على الحدث',
    shortAr: 'أفعال تبدأ بحدث', status: 'dev', priority: 'p1',
    desc: 'رحلات تلقائية تبدأ بحدث: سجّل → إيميل ترحيب → واتساب بعد 3 أيام → استبيان بعد أسبوع.',
    channels: ['email','whatsapp','sms'], useWith: ['مفتوح','هجين'], templates: ['welcome','reminder','feedback'] }),
  _f({ id: 'au.upgrade', family: 'automation', hue: 280, icon: '↑', name: 'تنبيهات ترقية وتجديد',
    shortAr: 'نبّه العضو في الوقت الصحيح', status: 'live', priority: 'p2',
    desc: 'رسائل ذكيّة عند اقتراب الحدّ أو انتهاء الاشتراك — تُقاس بمعدّل التحويل.',
    channels: ['email','whatsapp'], templates: ['upgrade-nudge'] }),

  // ===== Payments =====
  _f({ id: 'pm.checkout', family: 'payments', hue: 95, icon: '◐', name: 'صفحة دفع وتحصيل',
    shortAr: 'بطاقة · Apple Pay · Mada', status: 'planned', priority: 'p1',
    desc: 'صفحة دفع آمنة — متعدّدة الطرق، مع تأكيد فوري عبر الواتساب والإيميل.',
    channels: ['web','whatsapp','email'], templates: ['payment','payment-failed'] }),
  _f({ id: 'pm.invoice', family: 'payments', hue: 95, icon: '▢', name: 'فواتير ضريبية',
    shortAr: 'زاتكا-متوافقة — تُرسل آلياً', status: 'planned', priority: 'p1',
    desc: 'إصدار فاتورة ضريبية متوافقة مع هيئة الزكاة — إرسال تلقائي بعد كل عملية دفع.',
    channels: ['email'], templates: ['payment'] }),
  _f({ id: 'pm.failure', family: 'payments', hue: 0, icon: '✕', name: 'استرداد الدفعات الفاشلة',
    shortAr: 'حاول مجدّداً تلقائياً', status: 'planned', priority: 'p2',
    desc: 'عند فشل الدفع: رسالة فورية، روابط محاولة بديلة، متابعة بعد 24 سا.',
    channels: ['email','whatsapp'], templates: ['payment-failed'] }),

  // ===== AI =====
  _f({ id: 'ai.compose', family: 'ai', hue: 285, icon: '✻', name: 'صياغة محتوى بالذكاء الاصطناعي',
    shortAr: 'اكتب رسالتك بنقرة', status: 'planned', priority: 'p1',
    desc: 'AI يقترح صياغات متعدّدة للرسائل بناءً على النيّة واللهجة المطلوبة — رسمي، ودود، مختصر.',
    channels: ['inapp'] }),
  _f({ id: 'ai.translate', family: 'ai', hue: 285, icon: '⇋', name: 'ترجمة آلية عربي/إنجليزي',
    shortAr: 'ثنائي اللغة فورياً', status: 'idea', priority: 'p2',
    desc: 'ترجمة تلقائية للرسائل بين العربية والإنجليزية — مع الحفاظ على اللهجة الرسمية.',
    channels: ['inapp'] }),
  _f({ id: 'ai.faq_bot', family: 'ai', hue: 285, icon: '◎', name: 'ردّ ذكي على الواتساب',
    shortAr: 'FAQ Bot آلي', status: 'idea', priority: 'p2',
    desc: 'بوت يرد على الأسئلة الشائعة للأعضاء (مواعيد، روابط، تفاصيل) — يُحوّل للإنسان عند الحاجة.',
    channels: ['whatsapp'] }),
  _f({ id: 'ai.segment_suggest', family: 'ai', hue: 285, icon: '⊞', name: 'اقتراح شرائح ذكي',
    shortAr: 'AI يقترح من يستهدف', status: 'idea', priority: 'p3',
    desc: 'قبل إرسال حملة، AI يقترح الشريحة الأنسب من سلوك الأعضاء السابق.',
    channels: ['inapp'] }),

  // ===== Brand =====
  _f({ id: 'br.whitelabel', family: 'brand', hue: 0, icon: '◆', name: 'علامة بيضاء كاملة',
    shortAr: 'هوية العميل — لا هوية محور', status: 'live', priority: 'p0',
    desc: 'كل الرسائل والصفحات والمستندات تحمل هوية العميل حصرياً — بلا ذكر محور للأعضاء.',
    channels: ['web','email','whatsapp','sms'], useWith: ['مفتوح','مغلق','هجين'] }),
  _f({ id: 'br.theme', family: 'brand', hue: 0, icon: '◈', name: 'ثيم وألوان مخصّصة',
    shortAr: 'لون · خط · شعار', status: 'live', priority: 'p1',
    desc: 'تخصيص لون رئيسي وخطّ وشعار لكل مجتمع — تطبّق تلقائياً في كل القوالب.',
    channels: ['web','email'] }),
  _f({ id: 'br.domain', family: 'brand', hue: 0, icon: '◉', name: 'نطاق مخصّص',
    shortAr: 'your.brand — بدل mhwar.sa', status: 'planned', priority: 'p1',
    desc: 'ربط نطاق العميل (your.brand) لصفحات المجتمع والفعاليات — مع شهادة SSL تلقائية.',
    channels: ['web'] }),

  // ===== Legal & Reference =====
  _f({ id: 'lg.terms', family: 'legal', hue: 230, icon: '§', name: 'الشروط والأحكام',
    shortAr: 'اتفاقية استخدام المنصّة', status: 'live', priority: 'p0',
    desc: 'الإطار القانوني الذي يحكم استخدام العملاء للمنصّة — منشور على mhwar.com/terms.',
    channels: ['web'] }),
  _f({ id: 'lg.privacy', family: 'legal', hue: 230, icon: '§', name: 'سياسة الخصوصية',
    shortAr: 'حماية بيانات الأعضاء', status: 'live', priority: 'p0',
    desc: 'كيف تجمع منصّة محور البيانات الشخصية، وكيف تستخدمها، وحقوق أصحابها — منشورة على mhwar.com/privacy.',
    channels: ['web'] }),
  _f({ id: 'lg.pdpl', family: 'legal', hue: 230, icon: '⎔', name: 'توافق PDPL السعودي',
    shortAr: 'نظام حماية البيانات الشخصية', status: 'dev', priority: 'p0',
    desc: 'مطابقة كاملة للّوائح السعودية لحماية البيانات — ضوابط وصول، تشفير، سجلات تدقيق، إشعار خرق.',
    channels: ['web'], notes: 'ضروري لقبول أي عميل حكومي أو تنظيمي' }),
  _f({ id: 'lg.dpa', family: 'legal', hue: 230, icon: '▦', name: 'اتفاقية معالجة البيانات (DPA)',
    shortAr: 'نموذج موقّع لكل عميل', status: 'planned', priority: 'p1',
    desc: 'اتفاقية موقّعة بين محور والعميل تحدّد دور كل طرف كمتحكّم ومعالج — شرط تعاقدي للقطاع المؤسّسي.',
    channels: ['email','web'] }),
  _f({ id: 'lg.subprocessors', family: 'legal', hue: 230, icon: '⊸', name: 'قائمة المعالجين الفرعيين',
    shortAr: 'شفافية مع Meta · AWS · …', status: 'planned', priority: 'p1',
    desc: 'صفحة علنية بكل الأطراف الثالثة التي تعالج بيانات العميل — مع إشعار مسبق قبل أي تغيير.',
    channels: ['web'] }),
  _f({ id: 'lg.dpr', family: 'legal', hue: 230, icon: '◉', name: 'طلبات أصحاب البيانات',
    shortAr: 'وصول · تصحيح · حذف — آلي', status: 'planned', priority: 'p1',
    desc: 'نموذج ذاتي الخدمة يتيح لأي عضو طلب نسخة من بياناته أو تصحيحها أو حذفها — مع SLA محدّد للاستجابة.',
    channels: ['web','email'] }),
  _f({ id: 'lg.consent_log', family: 'legal', hue: 230, icon: '✓', name: 'سجلّ موافقات الأعضاء',
    shortAr: 'دليل قبول قابل للتدقيق', status: 'dev', priority: 'p1',
    desc: 'كل موافقة (اشتراك، opt-in، قبول شروط) تُسجّل مع الطابع الزمني و IP — دليل قانوني عند النزاع.',
    channels: ['web'] }),
  _f({ id: 'lg.retention', family: 'legal', hue: 230, icon: '↺', name: 'سياسة الاحتفاظ والحذف',
    shortAr: 'حذف آلي بعد انتهاء الغرض', status: 'planned', priority: 'p2',
    desc: 'جداول احتفاظ واضحة لكل نوع بيانات — وحذف آلي بمجرّد انتهاء الغرض أو المدة المحدّدة.',
    channels: ['web'] }),
  _f({ id: 'lg.trust', family: 'legal', hue: 230, icon: '◆', name: 'مركز الثقة (Trust Center)',
    shortAr: 'شفافية أمنية وامتثال', status: 'idea', priority: 'p2',
    desc: 'صفحة علنية تجمع كل ما يخص الأمن والامتثال: شهادات، سياسات، حالة النظام، إشعارات خرق.',
    channels: ['web'] }),
  _f({ id: 'lg.soc2', family: 'legal', hue: 230, icon: '◈', name: 'شهادة SOC 2 / ISO 27001',
    shortAr: 'اعتماد أمني دولي', status: 'idea', priority: 'p3',
    desc: 'اعتماد أمني دولي يفتح أبواب القطاع المؤسّسي العالمي — يتطلّب ٦-١٢ شهراً وتدقيق مستقل.',
    channels: ['web'] }),
];

Object.assign(window, {
  UC_FEATURES_SEED,
  UC_FEATURE_FAMILIES,
  UC_FEATURE_STATUSES,
  UC_FEATURE_PRIORITIES,
});
